### ISSUE TITLE
Current Automation swagger spec has inconsistency in defining pageable extension for AutomationAccounts_ListBySubscriptionId and AutomationAccounts_ListByResourceGroup

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-rest-api-specs#1070]
- [AutomationAccounts_ListBySubscriptionId](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-automation/2015-10-31/swagger/account.json#L289) has 
```json5
"x-ms-pageable": {
    "nextLinkName": null
 }
```

and 

- [AutomationAccounts_ListByResourceGroup](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-automation/2015-10-31/swagger/account.json#L217) has
```json5
"x-ms-pageable": {
   "nextLinkName": "nextLink"
}
```

which is inconsistent. ListBySubscriptionId is at a bigger scope and must be pageable as well.

We should have a linter rule to catch such issues.

Currently this fails the nodejs cogeneration with the error
```
FATAL: Error saving generated code: System.Exception: Duplicate File Generation: models/automationAccountListResult.js
   at AutoRest.Core.CodeGenerator.<Write>d__13.MoveNext() in /Users/amarz/sdk/AutoRest/src/core/AutoRest.Core/CodeGenerator.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AutoRest.Core.CodeGenerator.<Write>d__12.MoveNext() in /Users/amarz/sdk/AutoRest/src/core/AutoRest.Core/CodeGenerator.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AutoRest.NodeJS.Azure.CodeGeneratorJsa.<Generate>d__5.MoveNext() in /Users/amarz/sdk/AutoRest/src/generator/AutoRest.NodeJS.Azure/CodeGeneratorJsa.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AutoRest.Core.AutoRestController.Generate() in /Users/amarz/sdk/AutoRest/src/core/AutoRest.Core/AutoRestController.cs:line 98
```

**Comment by amarzavery** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/1081
