### ISSUE TITLE
Microsoft.Storage API spec does not work with autorest

### ISSUE THREAD

**Issue by rjmholt** [Azure/azure-rest-api-specs#10979]
From https://github.com/Azure/autorest.modelerfour/issues/303.

I have a custom autorest plugin that is able to process other Azure REST API specs. When I run it on the Microsoft.Storage spec like this:

```
autorest https://github.com/Azure/azure-rest-api-specs/tree/master/specification/storage/resource-manager --use:. --tag=package-2019-06 --debug
```

I get the following:

```
DEBUG [8.28 s]: modelerfour - END [0.63 s]
DEBUG [8.28 s]: modelerfour/new-transform - START inputs = 2
DEBUG [8.28 s]: modelerfour/new-transform - END [0 s]
DEBUG [8.28 s]: modelerfour/flattener - START inputs = 2
DEBUG [8.61 s]: modelerfour/flattener - END [0.32 s]
DEBUG [8.61 s]: modelerfour/flattener/new-transform - START inputs = 2
DEBUG [8.61 s]: modelerfour/flattener/new-transform - END [0 s]
DEBUG [8.61 s]: modelerfour/grouper - START inputs = 2
DEBUG [8.91 s]: modelerfour/grouper - END [0.29 s]
DEBUG [8.91 s]: modelerfour/grouper/new-transform - START inputs = 2
DEBUG [8.91 s]: modelerfour/grouper/new-transform - END [0 s]
DEBUG [8.91 s]: modelerfour/pre-namer - START inputs = 2
DEBUG [9.2 s]: modelerfour/pre-namer - END [0.28 s]
DEBUG [9.2 s]: modelerfour/pre-namer/new-transform - START inputs = 2
DEBUG [9.2 s]: modelerfour/pre-namer/new-transform - END [0 s]
DEBUG [9.2 s]: modelerfour/checker - START inputs = 2

WARNING (): Schema Missing Name '{"type":"constant","value":{"value":"default"},"valueType":{"type":"string","language":{"default":{"name":"string","description":"simple string"}},"protocol":{}},"language":{"default":{"name":"","description":""}},"protocol":{}}'.
C:\Users\Robert Holt\.autorest\@autorest_modelerfour@4.13.312\node_modules\@autorest\modelerfour\dist\checker\plugin-checker.js - FAILURE  {} Error: 4 errors occured -- cannot continue.
    at Session.checkpoint (/node_modules/@azure-tools/autorest-extension-base/dist/convenience.js:158:19)
    at processRequest (C:\Users\Robert Holt\.autorest\@autorest_modelerfour@4.13.312\node_modules\@autorest\modelerfour\dist\checker\plugin-checker.js:21:17)
    at async /node_modules/@azure-tools/autorest-extension-base/dist/extension-base.js:42:17

ERROR (): Duplicate object schemas with 'BlobServiceProperties' name  detected.

ERROR (): Duplicate object schemas with 'FileServiceProperties' name  detected.

ERROR (): Duplicate object schemas with 'QueueServiceProperties' name  detected.

ERROR (): Duplicate object schemas with 'TableServiceProperties' name  detected.
PLUGIN FAILURE: 4 errors occured -- cannot continue., Error: 4 errors occured -- cannot continue.
    at Session.checkpoint (/node_modules/@azure-tools/autorest-extension-base/dist/convenience.js:158:19)
    at processRequest (C:\Users\Robert Holt\.autorest\@autorest_modelerfour@4.13.312\node_modules\@autorest\modelerfour\dist\checker\plugin-checker.js:21:17)
    at async /node_modules/@azure-tools/autorest-extension-base/dist/extension-base.js:42:17, {}
FATAL: Error: 4 errors occured -- cannot continue.
C:\Users\Robert Holt\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Plugin checker reported failure. / Error: Plugin checker reported failure.
    at C:\Users\Robert Holt\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\plugins\external.js:26:19
    at async ScheduleNode (C:\Users\Robert Holt\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js:294:33)
  Error: Plugin checker reported failure.
```

This issue occurs before autorest runs my own plugin, and seems to be due to an issue in the spec itself. Unfortunately it means I have no way to process the Microsoft.Storage spec.

**Comment by blueww** [comment]
Generate .net SDK code from the swagger has no problem, following is the command:
`autorest https://github.com/Azure/azure-rest-api-specs/tree/master/specification/storage/resource-manager/readme.md  --csharp --version=2.0.4413 --reflect-api-versions --tag=package-2019-06 --csharp.output-folder=C:\code\srpsdk\sdk\storage\Microsoft.Azure.Management.Storage\src\Generated`
And other SDK generated on the swagger also success.

@rjmholt 
Is that caused by the autorest version, or some issue of the plugin?

@markcowl 
Do you have any idea?
