### ISSUE TITLE
Ruby CI test is failing

### ISSUE THREAD

**Issue by jaredmoo** [Azure/azure-rest-api-specs#1446]
Hitting this issue on https://github.com/Azure/azure-rest-api-specs/pull/1441, CI results at https://travis-ci.org/Azure/azure-rest-api-specs/builds/255431441?utm_source=github_status&utm_medium=notification 

```
Traceback (most recent call last):
  File "/SwaggerToSdkMain.py", line 142, in <module>
    main()
  File "/SwaggerToSdkMain.py", line 139, in main
    args.autorest_bin)
  File "/SwaggerToSdkMain.py", line 49, in generate_sdk
    sdk_repo, temp_dir, initial_pr, autorest_bin)
  File "/SwaggerToSdkNewCLI.py", line 228, in build_libraries
    autorest_bin)
  File "/SwaggerToSdkNewCLI.py", line 73, in generate_code
    raise ValueError("Autorest call ended with 0, but no files were generated")
ValueError: Autorest call ended with 0, but no files were generated
The command "if [[ $MODE == 'ruby' ]]; then $DOCKER_CMD AutorestCI/azure-sdk-for-ruby --pr-repo-id Azure/azure-sdk-for-ruby -o master -v; fi" exited with 1.
0.00s$ if [[ $MODE == 'syntax' ]]; then npm test -- test/syntax.js; fi
```

**Comment by balajikris** [comment]
tagging @sarangan12

**Comment by sarangan12** [comment]
@jaredmoo This issue has been fixed with recent merges, Closing this issue now. Feel free to reopen if you still find the issues
