### ISSUE TITLE
Issue while generating csharp code using autorest

### ISSUE THREAD

**Issue by suchandr1** [Azure/azure-rest-api-specs#1634]
I am facing issue while generating csharp code using autorest

autorest --csharp --csharp-sdks-folder="C:\azure-sdk-for-net\src\SDKs" --tag=package-2016-06

AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
FATAL: System.InvalidOperationException: Found incompatible property types Object, Object for property 'tags' in schema
inheritance chain
   at AutoRest.Swagger.SchemaResolver.ExpandAllOf(Schema schema)
   at AutoRest.Swagger.SchemaResolver.Unwrap(Schema schema)
   at AutoRest.Swagger.SchemaBuilder.BuildServiceType(String serviceTypeName)
   at AutoRest.Swagger.SwaggerModeler.BuildCompositeTypes()
   at AutoRest.Swagger.SwaggerModeler.Build(ServiceDefinition serviceDefinition)
   at Modeler.<ProcessInternal>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__11.MoveNext()
FATAL: csharp/modeler - FAILED
FATAL: Error: Plugin modeler reported failure.
Process() Cancelled due to exception : Plugin modeler reported failure.
Error: Plugin modeler reported failure.
    at C:\Users\suchandr\.autorest\plugins\autorest\1.2.2\node_modules\autorest-core\lib\pipeline\pipeline.js:90:19
    at next (native)
    at fulfilled (C:\Users\suchandr\AppData\Roaming\npm\node_modules\autorest\lib\polyfill.min.js:14:62)

Can some one please help me to figure out what I am missing here?

**Comment by suchandr1** [comment]
Attaching folder in which I am running above mentioned command.

[resource-manager.zip](https://github.com/Azure/azure-rest-api-specs/files/1277860/resource-manager.zip)

**Comment by olydis** [comment]
@suchandr1 looking into it

**Comment by olydis** [comment]
Not sure if that's the cause, but I noticed something very odd:
`Vault` in `RRP.json` has a property `etag` but also inherits from `Resource` which has a property `eTag`. At least adjust the spelling, also be aware that setting `etag` to readonly will not work since the property lives in the base class.

**Comment by olydis** [comment]
Closing due to inactivity. Please reopen if the problem persists.
