### ISSUE TITLE
[TypeSpec Validation] "tsv ." fails with path error

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-rest-api-specs#26546]
On Ubuntu 22:

```
mharder@mharder-dev-u22:~/specs/specification/vision/ImageAnalysis$ npx tsv .
Running TypeSpecValidation on folder: .

Executing rule: FolderStructure
file:///home/mharder/specs/eng/tools/TypeSpecValidation/dist/src/rules/folder-structure.js:40
            if (folderStruct[1].match(/[A-Z]/g)) {
                                ^

TypeError: Cannot read properties of undefined (reading 'match')
    at FolderStructureRule.<anonymous> (file:///home/mharder/specs/eng/tools/TypeSpecValidation/dist/src/rules/folder-structure.js:40:33)
    at Generator.next (<anonymous>)
    at fulfilled (file:///home/mharder/specs/eng/tools/TypeSpecValidation/dist/src/rules/folder-structure.js:4:58)

Node.js v18.18.2
```

**Comment by ckairen** [comment]
should we be allowing this operation though? "." implies cwd() but I don't think there's built in conversion from dot to cwd when running typescript.
