### ISSUE TITLE
No networking interface Properties provided

### ISSUE THREAD

**Issue by sylr** [Azure/azure-rest-api-specs#4404]
This issue has previously been opened at https://github.com/prometheus/prometheus/issues/4779 because it's the software that revealed the symptom.

In a few words it happens (very occasionally with no obvious reason) that [client.getNetworkInterfaceByID(*nic.ID)](https://github.com/prometheus/prometheus/blob/167a4b4e73a8eca8df648d2d2043e21bdb9a7449/discovery/azure/azure.go#L310) returns an object with and empty `Properties` property which makes the software panic.

```
level=error ts=2018-10-24T03:46:32.164842306Z caller=engine.go:526 component="query engine" msg="error expanding series set" err="context canceled"
level=error ts=2018-10-24T04:21:26.967205519Z caller=api.go:1013 component=web msg="error writing response" bytesWritten=0 err="write tcp 10.199.0.149:9090->10.100.3.133:50800: write: broken pipe"
level=error ts=2018-10-24T04:30:03.85725554Z caller=engine.go:526 component="query engine" msg="error expanding series set" err="context canceled"
level=error ts=2018-10-24T04:30:04.864806469Z caller=engine.go:526 component="query engine" msg="error expanding series set" err="context canceled"
level=error ts=2018-10-24T06:01:34.044734663Z caller=engine.go:526 component="query engine" msg="error expanding series set" err="context canceled"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8e80c8]
goroutine 3621262 [running]:
github.com/prometheus/prometheus/discovery/azure.(*Discovery).refresh.func2(0xc05cc34b70, 0xc07237e960, 0xc0a25a0b00, 0x11, 0xc06766b860, 0x9b, 0xc00ae86aa0, 0x16, 0xc02932f380, 0x21, ...)
	/go/src/github.com/prometheus/prometheus/discovery/azure/azure.go:322 +0x588
created by github.com/prometheus/prometheus/discovery/azure.(*Discovery).refresh
	/go/src/github.com/prometheus/prometheus/discovery/azure/azure.go:282 +0x674
```

https://github.com/prometheus/prometheus/blob/167a4b4e73a8eca8df648d2d2043e21bdb9a7449/discovery/azure/azure.go#L322-L326

**Comment by dmitsh** [comment]
I will look into this and submit a PR
