### ISSUE TITLE
LocalSearch model validation causes crash

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#4878]
Same as #4856, running model validation on this swagger folder causes a crash.
Running with `node --max-old-space-size=8192 scripts/modelValidation.js` gives a slightly different error
```
(node:1456) UnhandledPromiseRejectionWarning: RangeError: Invalid string length
    at join (internal/util.js:311:20)
    at reduceToSingleString (internal/util/inspect.js:1094:15)
    at formatRaw (internal/util/inspect.js:702:10)
    at formatValue (internal/util/inspect.js:471:10)
    at formatProperty (internal/util/inspect.js:1028:11)
    at formatRaw (internal/util/inspect.js:684:11)
    at formatValue (internal/util/inspect.js:471:10)
    at formatProperty (internal/util/inspect.js:1028:11)
    at formatRaw (internal/util/inspect.js:684:11)
    at formatValue (internal/util/inspect.js:471:10)
(node:1456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Removing the `x-ms-example` does allow it to pass, but it doesn't seem like anything in the example should cause it to crash.

PS: The very similar `NewsSearch` doesn't seem to crash

**Comment by nschonni** [comment]
@sergey-shandar will #5012 also address this, or is it a separate root cause?
