### ISSUE TITLE
Breaking changes CI check is failing with assembly error exception

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#5204]
CI for Breaking changes job is failing in the repo with https://travis-ci.org/Azure/azure-rest-api-specs/jobs/493378789#L836 Needs investigation and fix.
```

{ Error: Command failed: dotnet /home/travis/build/Azure/azure-rest-api-specs/node_modules/oad/lib/dlls/OpenApiDiff.dll -o /tmp/old.json -n /tmp/new.json -JsonValidationMessages

Error:

  An assembly specified in the application dependencies manifest (OpenApiDiff.deps.json) was not found:

    package: 'Newtonsoft.Json', version: '9.0.1'

    path: 'lib/netstandard1.0/Newtonsoft.Json.dll'


    at ChildProcess.exithandler (child_process.js:281:12)

    at emitTwo (events.js:126:13)

    at ChildProcess.emit (events.js:214:7)

    at maybeClose (internal/child_process.js:915:16)

    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

  killed: false,

  code: 140,

  signal: null,

  cmd: 'dotnet /home/travis/build/Azure/azure-rest-api-specs/node_modules/oad/lib/dlls/OpenApiDiff.dll -o /tmp/old.json -n /tmp/new.json -JsonValidationMessages' }
```

**Comment by salameer** [comment]
Hi @veronicagg please track this internally in Devops
