### ISSUE TITLE
0.10.6: The hosted service does not exist (Cannot read property 'length' of undefined)

### ISSUE THREAD

**Issue by joergrech** [Azure/azure-rest-api-specs#614]
Since ~11 AM today (20 Oct. 2016) we cannot run azure commands anymore (MacOS Sierra 10.12). We started several server and suddenly the script gave the following error (no changes were made to the script). 

The following output comes from our script that first deletes a server (e.g., tw-crawler-010) and then creates a new one with the same name - lines starting with "Deleting on" or "Starting on" and "Time passed" are ours the rest comes from "azure vm delete -b -q" and "azure vm create"

```sh
...
Deleting on Thu Oct 20 10:53:29 CEST 2016 instance tw-crawler-010
\info:    Executing command vm delete
info:    Executing command vm create
+ Looking up image tw-crawler-neu3                                             
+ Deleting Cloud Service                                                       
+ Looking up cloud service                                                     
info:    vm delete command OK
+
info:    cloud service tw-crawler-009 not found.
info:    using the VM image location North Europe
+ Creating cloud service                                                       
+\Configuring certificate                                                      
+ Deleting VM                                                                  
/Starting on Thu Oct 20 10:54:19 CEST 2016 instance tw-crawler-010             
Time passed: 8 minutes
Deleting on Thu Oct 20 10:54:19 CEST 2016 instance tw-crawler-011
-info:    Executing command vm delete
info:    Executing command vm create
+ Looking up image tw-crawler-neu3                                             
+/Looking up cloud service                                                     
+
+ Deleting Cloud Service                                                       
+|Looking up deployment                                                        
info:    vm delete command OK
+
+ Configuring certificate                                                      
\data:    {VM                                                                  
data:        stack: 'Error: The hosted service does not exist.\n    at Function.ServiceClient._normalizeError (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:814:23)\n    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29\n    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)\n    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:187:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:1044:10)\n    at emitOne (events.js:101:20)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:965:12)',
data:        message: 'The hosted service does not exist.',
data:        code: 'ResourceNotFound',
data:        statusCode: 404,
data:        requestId: '6e32ab31bbbf020499775a5cb644d0ff'
data:    }
error:   Error: The hosted service does not exist.
error:   Error information has been recorded to /Users/jorgrech/.azure/azure.err
error:   vm create command failed

+
info:    vm create command OK
+
Starting on Thu Oct 20 10:55:09 CEST 2016 instance tw-crawler-011
Time passed: 9 minutes
Deleting on Thu Oct 20 10:55:09 CEST 2016 instance tw-crawler-012
-info:    Executing command vm create                                          
\info:    Executing command vm delete
+ Looking up image tw-crawler-neu3                                             
info:    vm delete command OK
+
+ Looking up cloud service                                                     
info:    cloud service tw-crawler-011 not found.
info:    using the VM image location North Europe
+ Creating cloud service                                                       
| Configuring certificate                                                      
<--- Last few GCs --->

   24283 ms: Mark-sweep 1377.3 (1413.0) -> 1368.9 (1414.0) MB, 39.1 / 0 ms [allocation failure] [GC in old space requested].
   24319 ms: Mark-sweep 1368.9 (1414.0) -> 1368.9 (1415.0) MB, 36.4 / 0 ms [allocation failure] [GC in old space requested].
   24353 ms: Mark-sweep 1368.9 (1415.0) -> 1368.8 (1415.0) MB, 33.9 / 0 ms [last resort gc].
   24385 ms: Mark-sweep 1368.8 (1415.0) -> 1368.8 (1415.0) MB, 31.7 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2703849c9e59 <JS Object>
    1: SparseJoinWithSeparatorJS(aka SparseJoinWithSeparatorJS) [native array.js:~84] [pc=0x3d1befc90b90] (this=0x270384904189 <undefined>,w=0x272f1feea889 <JS Array[11233]>,L=11233,M=0x2703849b4ad9 <JS Function ConvertToString (SharedFunctionInfo 0x27038494ef79)>,N=0x1482e3df2151 <String[4]\: ,\n  >)
    2: Join(aka Join) [native array.js:143] [pc=0x3d1befce5d76] (this=0x270384904189 <undefine...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
+
-./azure_exchange_instances.sh: line 20: 17371 Abort trap: 6           azure vm delete -b -q $instanceName
Starting on Thu Oct 20 10:55:59 CEST 2016 instance tw-crawler-012
Time passed: 10 minutes
Deleting on Thu Oct 20 10:55:59 CEST 2016 instance tw-crawler-013
\info:    Executing command vm delete
info:    Executing command vm create
- Getting virtual machineserror:   Cannot read property 'length' of undefined  
error:   Error information has been recorded to /Users/jorgrech/.azure/azure.err
error:   vm delete command failed

|error:   Cannot read property 'length' of undefined                           
error:   Error information has been recorded to /Users/jorgrech/.azure/azure.err
error:   vm create command failed

|Starting on Thu Oct 20 10:56:49 CEST 2016 instance tw-crawler-013
Time passed: 10 minutes
...
```

I don't have the original azure.err file but the azure.err file for "azure vm delete -b -q instance tw-crawler-003" says:

```sh
when executing any azure command I get the "TypeError":
2016-10-20T17:54:09.928Z:
TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:162:41
    at /usr/local/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:187:25
    at /usr/local/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:53:7
    at FileTokenStorage._.extend.loadEntries (/usr/local/lib/node_modules/azure-cli/lib/util/authentication/file-token-storage.js:58:5)
    at TokenCache._.extend._loadEntries (/usr/local/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:48:24)
    at TokenCache.find (/usr/local/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:186:10)
    at CacheDriver._find (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:140:15)
    at CacheDriver._getPotentialEntries (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:161:8)
    at CacheDriver._loadSingleEntryFromCache (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:194:8)
    at CacheDriver.find (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:352:8)
TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:162:41
    at /usr/local/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:187:25
    at /usr/local/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:53:7
    at FileTokenStorage._.extend.loadEntries (/usr/local/lib/node_modules/azure-cli/lib/util/authentication/file-token-storage.js:58:5)
    at TokenCache._.extend._loadEntries (/usr/local/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:48:24)
    at TokenCache.find (/usr/local/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:186:10)
    at CacheDriver._find (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:140:15)
    at CacheDriver._getPotentialEntries (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:161:8)
    at CacheDriver._loadSingleEntryFromCache (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:194:8)
    at CacheDriver.find (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:352:8)
```

azure was installed using "npm install -g azure-cli" and I tried "Azure config mode arm" (but the azure delete command seems to switch to asm "info:    New mode is asm")

**Comment by joergrech** [comment]
Btw. I tried "azure login" as a test and got the following error in azure.err:

```
2016-10-20T18:22:41.277Z:
{ SyntaxError: Unexpected end of JSON input
  <<< async stack >>>
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/login.js:116:28)
  <<< raw stack >>>
    at Object.parse (native)
    at FileTokenStorage._.extend.loadEntries (/usr/local/lib/node_modules/azure-cli/lib/util/authentication/file-token-storage.js:49:22)
    at TokenCache._.extend._loadEntries (/usr/local/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:48:24)
    at TokenCache.find (/usr/local/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:186:10)
    at CacheDriver._find (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:140:15)
    at CacheDriver._findMRRTTokensForUser (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:174:8)
    at CacheDriver._updateRefreshTokens (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:431:10)
    at CacheDriver.add (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:506:8)
    at TokenRequest._addTokenIntoCache (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/token-request.js:173:23)
    at /usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/token-request.js:596:13
  stack: [Getter/Setter],
  __frame: 
   { name: '__1',
     line: 50,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/login.js',
     prev: undefined,
     calls: 0,
     active: false,
     offset: 66,
     col: 27 },
  rawStack: [Getter] }
SyntaxError: Unexpected end of JSON input
  <<< async stack >>>
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/login.js:116:28)
  <<< raw stack >>>
    at Object.parse (native)
    at FileTokenStorage._.extend.loadEntries (/usr/local/lib/node_modules/azure-cli/lib/util/authentication/file-token-storage.js:49:22)
    at TokenCache._.extend._loadEntries (/usr/local/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:48:24)
    at TokenCache.find (/usr/local/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:186:10)
    at CacheDriver._find (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:140:15)
    at CacheDriver._findMRRTTokensForUser (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:174:8)
    at CacheDriver._updateRefreshTokens (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:431:10)
    at CacheDriver.add (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:506:8)
    at TokenRequest._addTokenIntoCache (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/token-request.js:173:23)
    at /usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/token-request.js:596:13

```

**Comment by amarzavery** [comment]
@joergrech - This issue needs to be filed in the azure-xplat-cli repo. This is an incorrect repo. 
https://github.com/Azure/azure-rest-api-specs/issues/614

**Comment by joergrech** [comment]
Sorry.
