### ISSUE TITLE
ApiManagement 2018-06-01-preview

### ISSUE THREAD

**Issue by MyronFanQiu** [Azure/azure-rest-api-specs#6713]
https://github.com/Azure/azure-rest-api-specs/blob/2fcd0139889b923094b39a6aae015e1ea3604b68/specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2018-06-01-preview/apimcaches.json#L86

There is some restriction that if you provide the x-ms-odata in the swagger file, you need support "$filter" parameter in this path.
```
FATAL: System.InvalidOperationException: Method 'Cache_ListByService' with x-ms-odata needs to have "$filter" parameter.
   at AutoRest.Extensions.Azure.AzureExtensions.ParseODataExtension(CodeModel codeModel) in /home/ruby/autorest.ruby/autorest.common/src/AzureExtensions.cs:line 187
   at AutoRest.Extensions.Azure.AzureExtensions.NormalizeAzureClientModel(CodeModel codeModel) in /home/ruby/autorest.ruby/autorest.common/src/AzureExtensions.cs:line 77
   at AutoRest.Ruby.Azure.TransformerRba.AutoRest.Core.ITransformer<AutoRest.Ruby.Azure.Model.CodeModelRba>.TransformCodeModel(CodeModel cs) in /home/ruby/autorest.ruby/src/azure/TransformerRba.cs:line 40
   at AutoRest.Ruby.Program.<ProcessInternal>d__4.MoveNext() in /home/ruby/autorest.ruby/src/Program.cs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NewPlugin.<Process>d__20.MoveNext() in /home/ruby/autorest.ruby/autorest.common/src/Plugins/NewPlugin.cs:line 163
```

**Comment by yungezz** [comment]
fixed by referenced PR close this.
