### ISSUE TITLE
[Network] loadBalancerFrontendIpConfigurations in private link service

### ISSUE THREAD

**Issue by MyronFanQiu** [Azure/azure-rest-api-specs#6988]
```
2019-08-16T09:47:30.9973286Z ERROR: test_network_private_link_service (azure.cli.command_modules.network.tests.latest.test_network_commands.NetworkPrivateLinkService)
2019-08-16T09:47:30.9974148Z ----------------------------------------------------------------------
2019-08-16T09:47:30.9974623Z Traceback (most recent call last):
2019-08-16T09:47:30.9975408Z   File "/opt/hostedtoolcache/Python/2.7.16/x64/lib/python2.7/site-packages/azure_devtools/scenario_tests/preparers.py", line 50, in _preparer_wrapper
2019-08-16T09:47:30.9975876Z     fn(test_class_instance, **kwargs)
2019-08-16T09:47:30.9976709Z   File "/opt/hostedtoolcache/Python/2.7.16/x64/lib/python2.7/site-packages/azure/cli/command_modules/network/tests/latest/test_network_commands.py", line 162, in test_network_private_link_service
2019-08-16T09:47:30.9977506Z     self.check('length(loadBalancerFrontendIpConfigurations)', 1)
2019-08-16T09:47:30.9978706Z   File "/opt/hostedtoolcache/Python/2.7.16/x64/lib/python2.7/site-packages/azure/cli/testsdk/base.py", line 161, in cmd
2019-08-16T09:47:30.9979292Z     return execute(self.cli_ctx, command, expect_failure=expect_failure).assert_with_checks(checks)
2019-08-16T09:47:30.9980311Z   File "/opt/hostedtoolcache/Python/2.7.16/x64/lib/python2.7/site-packages/azure/cli/testsdk/base.py", line 201, in __init__
2019-08-16T09:47:30.9980822Z     self._in_process_execute(cli_ctx, command, expect_failure=expect_failure)
2019-08-16T09:47:30.9981872Z   File "/opt/hostedtoolcache/Python/2.7.16/x64/lib/python2.7/site-packages/azure/cli/testsdk/base.py", line 264, in _in_process_execute
2019-08-16T09:47:30.9982279Z     raise ex.exception
2019-08-16T09:47:30.9983050Z SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

It seems that the response of the creation of private link service cannot be correctly parsed as a model.

**Comment by number213** [comment]
I think this is caused by incorrect type of "loadBalancerFrontendIpConfigurations" which should be an ID reference and not whole resource.
@MyronFanQiu could you please try running test with SDK generated from this https://github.com/Azure/azure-rest-api-specs/pull/6999 ? I see that the error only occurs in Python 2 but I couldn't figure out how to run tests with it.
