### ISSUE TITLE
Azure Stack - Microsoft.Subscriptions.Admin LinkedAction enum has wrong name

### ISSUE THREAD

**Issue by pbolduc** [Azure/azure-rest-api-specs#7822]
I was trying to generate client library for Azure Stack Admin Microsoft.Subscriptions.Admin and got an error from Autorest.  The error appears to because the LinkedAction enumeration has the wrong x-ms-enum name.  The name is duplicated from the ResourceDeletionPolicy enumeration.

https://github.com/Azure/azure-rest-api-specs/blob/1551635dddc7ed977a43eb79175ab2fc477f7bc7/specification/azsadmin/resource-manager/subscriptions/Microsoft.Subscriptions.Admin/preview/2015-11-01/Manifest.json#L655-L665

https://github.com/Azure/azure-rest-api-specs/blob/1551635dddc7ed977a43eb79175ab2fc477f7bc7/specification/azsadmin/resource-manager/subscriptions/Microsoft.Subscriptions.Admin/preview/2015-11-01/Manifest.json#L467-L475

```
C:\Users\phil\source\repos\azure-rest-api-specs\specification\azsadmin\resource-manager\subscriptions>autorest --python
AutoRest code generation utility [version: 2.0.4407; node: v10.16.3]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\phil\.autorest\@microsoft.azure_autorest-core@2.0.4407\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4407)
   Loading AutoRest extension '@microsoft.azure/autorest.python' (~3.0.56->3.0.62)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.44->2.3.44)
FATAL: System.InvalidOperationException: Swagger document contains two or more x-ms-enum extensions with the same name 'ResourceDeletionPolicy' and different values: NotSpecified,Cascade vs. NotSpecified,Blocked,Validate,Enabled
   at AutoRest.Modeler.ObjectBuilder.BuildServiceType(String serviceTypeName, Boolean required) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\ObjectBuilder.cs:line 147
   at AutoRest.Modeler.SchemaBuilder.ParentBuildServiceType(String serviceTypeName, Boolean required) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\SchemaBuilder.cs:line 217
   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName, Boolean required) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\SchemaBuilder.cs:line 48
   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName, Boolean required) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\SchemaBuilder.cs:line 133
   at AutoRest.Modeler.ObjectBuilder.BuildServiceType(String serviceTypeName, Boolean required) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\ObjectBuilder.cs:line 179
   at AutoRest.Modeler.SchemaBuilder.ParentBuildServiceType(String serviceTypeName, Boolean required) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\SchemaBuilder.cs:line 217
   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName, Boolean required) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\SchemaBuilder.cs:line 48
   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName, Boolean required) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\SchemaBuilder.cs:line 133
   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName, Boolean required) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\SchemaBuilder.cs:line 133
   at AutoRest.Modeler.ObjectBuilder.BuildServiceType(String serviceTypeName, Boolean required) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\ObjectBuilder.cs:line 179
   at AutoRest.Modeler.SchemaBuilder.ParentBuildServiceType(String serviceTypeName, Boolean required) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\SchemaBuilder.cs:line 217
   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName, Boolean required) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\SchemaBuilder.cs:line 48
   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName, Boolean required) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\SchemaBuilder.cs:line 133
   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName, Boolean required) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\SchemaBuilder.cs:line 133
   at AutoRest.Modeler.SwaggerModeler.BuildCompositeTypes() in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\SwaggerModeler.cs:line 310
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\SwaggerModeler.cs:line 66
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: python/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
Process() cancelled due to exception : Plugin imodeler1 reported failure.
  Error: Plugin imodeler1 reported failure.
```

**Comment by pbolduc** [comment]
Also ManifestProvisioningState enumeration has the wrong name

https://github.com/Azure/azure-rest-api-specs/blob/e0996d4f6dbca40ebf2fa4abf9a1cba45ada94d8/specification/azsadmin/resource-manager/subscriptions/Microsoft.Subscriptions.Admin/preview/2015-11-01/Manifest.json#L866-L878

Once I fixed these locally, Autorest ran to completion.

**Comment by xccc-msft** [comment]
@deathly809 can you please verify above issues?

**Comment by bganapa** [comment]
Hi @pbolduc , We will fix this issue. Could you please clarify what you are trying to do with a generated library. At the moment, we are of the opinion that Azure Stack admin api users are mainly powershell/ .NET users.

**Comment by pbolduc** [comment]
At my current client, we are using Nagios to monitor Azure Stack Hub. Among other things, I was looking to monitor the number of active and disabled user subscriptions.  For this case, I was using Python for creating the plugin. An alternative use case we have is when creating user subscriptions. In our environment, all user subscriptions will be owned (ie billing owner) by a single account. The real owners will be assigned as owners or contributors within the subscription.  By taking this approach we will still have access to each user subscription for monitoring and compliance reasons.  We may use PowerShell, but it is tricky switching between context between adminmanagement and the management environments. We will want to automate these user subscription creation. We need to create the subscription in adminmanagement  and then authenticate as the owner account in management to add the real end user.  Being able to generate client libraries in any supported language gives us more options.

In addition, I have found it difficult to identify the correct NuGet packages to use in .NET when working with Azure Stack.

**Comment by bganapa** [comment]
Thanks @pbolduc for the details.  The .NET package you are looking for is
https://www.nuget.org/packages/Microsoft.AzureStack.Management.Subscriptions.Admin/0.2.0-preview
This will help you create user subscriptions as an admin.
The powershell cmdlet that crates user subscription as a administrator is here 
https://docs.microsoft.com/en-us/powershell/module/azs.subscriptions.admin/new-azsusersubscription?view=azurestackps-1.7.2

**Comment by bganapa** [comment]
PR - https://github.com/Azure/azure-rest-api-specs/pull/7852

**Comment by xccc-msft** [comment]
@pbolduc can you try with latest json? The changes are merged to master now.

**Comment by pbolduc** [comment]
I am in Pacific time zone.  I will test tomorrow when I come into work.

**Comment by pbolduc** [comment]
This looks good, however, it does not appear to be merged into master yet.  I tested against branch [stackadmin](https://github.com/Azure/azure-rest-api-specs/tree/stackadmin/specification/azsadmin/resource-manager/subscriptions).  There appears to be another issue with the network generation due to the use of $(this-folder).  I will create a separate issue for that.  I tried on a Windows command prompt and a git bash session.

```
FATAL: Error: Could not read 'file:///C:/Users/phil/source/repos/azure-rest-api-specs/specification/azsadmin/resource-manager/network/$%28this-folder%29/Microsoft.Network.Admin/preview/2015-06-15/Network.json'.
Process() cancelled due to exception : Could not read 'file:///C:/Users/phil/source/repos/azure-rest-api-specs/specification/azsadmin/resource-manager/network/$%28this-folder%29/Microsoft.Network.Admin/preview/2015-06-15/Network.json
```
